### PR TITLE
feat: Recommended Ubuntu Version now 22.04 LTS

### LINKED ISSUE #81: Ubuntu Version
CE+ recommendation is to use 22.04.

Our [supported operating systems](https://github.com/TheDataShed/EngineeringHandbook/blob/main/policies/supported-operating-systems.md) still lists 20.04.

We should update this based on the latest guidance, as well as update our GitHub actions to use `ubuntu-22.04` too.

Gotcha: `ubuntu-latest` is \[currently\] pinned to `ubuntu-20.04` (see [here](https://github.com/actions/virtual-environments#available-environments)).

### PR DESCRIPTION
**Pull request by gvee-uk**
closes #81

### CODE REVIEW

**Review by KingMichaelPark — APPROVED** [review]

**Review by KingMichaelPark — APPROVED** [review]

**Review by GooseLF — APPROVED** [review]
LGTM 👍

Out of interest do we increment this version with each major release of Ubuntu? E.G 2023 this should go to 23.04, right?

**Comment by KingMichaelPark** [comment]
@GooseLF Only LTS releases a few months after they've been out. So the next will be 24.04

**Comment by gvee-uk** [comment]
> Out of interest do we increment this version with each major release of Ubuntu? E.G 2023 this should go to 23.04, right?

Not sure I can answer that - it would be on the advice from our Service Team (who do all the CE/CE+/ISO fun things)

**Comment by KingMichaelPark** [comment]
Approved by Glen

**Pull request merged**
