### PR TITLE
docs: Added TDS Acronym

### PR DESCRIPTION
**Pull request by gvee-uk**
~~Formatted the page to display items as an unordered list.~~

New addition to the list: TDS

### CODE REVIEW

**Review by GooseLF — APPROVED** [review]
LGTM 👍

**Review by PsypherPunk — APPROVED** [review]

**Comment by KingMichaelPark** [comment]
https://t.pxeger.com/mkdocs-material/reference/abbreviations/ This needs to stay formatted like this for it to render properly https://thedatashed.github.io/eng-hb-docs/standards/python-standards/ (See the AWS and GCP acronyms.) We can move it out of the rendered pages somewhere else though potentially?

**Comment by gvee-uk** [comment]
@KingMichaelPark I've reverted the formatting change so this PR is just introducing the TDS acronym instead.

**Comment by KingMichaelPark** [comment]
Thanks George, I will amend the structure to avoid that blank acronyms page when I can

**Pull request merged**
